### ISSUE TITLE
How to access error description?

### ISSUE THREAD

**Issue by michalrames** [campaignmonitor/createsend-java#39]
The following code sometimes fails for batch uploads. How do I access the error response to display the details of the error?
```
com.createsend.util.exceptions.BadRequestException: The CreateSend API responded with the following client error 210: Subscriber Import had some failures. Check resultData for more details
        at com.createsend.util.JerseyClientImpl.handleAPIErrorResponse(JerseyClientImpl.java:438) ~[createsend-java-5.1.3.jar!/:na]
        at com.createsend.util.JerseyClientImpl.handleErrorResponse(JerseyClientImpl.java:426) ~[createsend-java-5.1.3.jar!/:na]
        at com.createsend.util.JerseyClientImpl.post(JerseyClientImpl.java:271) ~[createsend-java-5.1.3.jar!/:na]
        at com.createsend.util.JerseyClientImpl.post(JerseyClientImpl.java:243) ~[createsend-java-5.1.3.jar!/:na]
        at com.createsend.util.JerseyClientImpl.post(JerseyClientImpl.java:218) ~[createsend-java-5.1.3.jar!/:na]
        at com.createsend.Subscribers.addMany(Subscribers.java:96) ~[createsend-java-5.1.3.jar!/:na]
```

This is the code leading to this exception:
```
Subscribers subscribersApi = new Subscribers(auth, listId);
SubscribersToAdd sta = new SubscribersToAdd();
// populate sta ...
ImportResult ir = subscribersApi.addMany(sta);  // <---- this throws the exception. The ImportResult is not accessible to parse the errors
```

Thank you

**Comment by michalrames** [comment]
I was capturing the more generic CreateSendException instead of the BadRequestException. BadRequestException provides access to the error message.
