### ISSUE TITLE
API 5.1.3 fails since yesterday: (HTTP Status: Not Acceptable)

### ISSUE THREAD

**Issue by patrickbucher** [campaignmonitor/createsend-java#48]
Without changing anything on our side, we cannot send out transactional email anymore since yesterday at roughly noon (CET):

```
Caused by: com.createsend.util.exceptions.CreateSendHttpException: The API call failed due to an unexpected HTTP error: Not Acceptable
    at com.createsend.util.JerseyClientImpl.handleUnknownError(JerseyClientImpl.java:431)
    at com.createsend.util.JerseyClientImpl.handleErrorResponse(JerseyClientImpl.java:422)
    at com.createsend.util.JerseyClientImpl.post(JerseyClientImpl.java:271)
    at com.createsend.util.JerseyClientImpl.post(JerseyClientImpl.java:243)
    at com.createsend.util.JerseyClientImpl.post(JerseyClientImpl.java:209)
    at com.createsend.SmartEmail.send(SmartEmail.java:118)
```

The error message is not helpful at all. However, I noticed that everything works (locally) when I update to the most recent API (6.0.2).

Was the old API (5.1.3) discontinued?

**Comment by markstaples** [comment]
Hi @patrickbucher, Campaign Monitor no longer supports HTTP for API requests - please use HTTPS. Endpoint URL in <= v.6.0.0 is set to HTTP. > v6.0.1 uses HTTPS. If you would like to continue to use v5.1.3, please update the following endpoint URL to http: https://github.com/campaignmonitor/createsend-java/blob/v5.1.3/src/com/createsend/util/config.properties#L2

**Comment by patrickbucher** [comment]
Thanks for the information, that answers my question. The migration to v6.0.2 was very easy, I only had to add the Constent flag to the actual API call.
Thank you!
